name: Проверка лейбла TestOk
on:
  pull_request:

jobs:
  message-check:
    name: Блокирование мерджа, если нет лейбла test-ok

    runs-on: ubuntu-latest

    steps:
      - name: Проверка лейблов
        uses: gpn-prototypes/block-pr-without-testok-label@testing
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
