name: Проверка лейбла TestOk
on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]

jobs:
  message-check:
    name: Блокирование мерджа, если нет лейбла test-ok

    runs-on: ubuntu-latest

    steps:
      - name: Проверка лейблов
        uses: gpn-prototypes/vega-actions/block-pr-without-testok-label@testing
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
