name: Публикация альфа версий
on:
  workflow_dispatch:

jobs:
  publish:
    name: Публикация новых версий
    runs-on: ubuntu-latest

    steps:
      - uses: docker://quay.csssr.cloud/csssr/github-info:v1
        id: gh

      - uses: actions/checkout@v2
        with:
          ref: refs/heads/${{ steps.gh.outputs.branch }}
          token: ${{ secrets.ADMIN_KEY }}

      - name: Скачивание всей git-истории (чтобы работал from-git)
        run: git fetch --prune --unshallow

      - name: Установка ноды
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Установка зависимостей
        run: yarn install --frozen-lockfile

      - name: Сборка пакетов
        run: yarn build

      - name: Публикация пакетов
        uses: gpn-prototypes/vega-actions/release-lerna-packages@master
        with:
          branch: ${{ steps.gh.outputs.branch }}
          main_branch: master
          gh_user: GitHub Workflow
          gh_email: workflow@github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.ADMIN_KEY }}
