name: Публикация альфа версий
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Ветка, с которой брать пакеты'
        required: true
        default: 'master'

jobs:
  publish:
    name: Публикация новых версий
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/heads/${{ github.event.inputs.branch }}
          token: ${{ secrets.ADMIN_KEY }}

           - name: Скачивание всей git-истории (чтобы работал from-git)
        run: git fetch --prune --unshallow


      - name: Установка ноды
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Установка зависимостей
        run: yarn install --frozen-lockfile

      - name: Сборка пакетов
        run: yarn build

      - name: Настройка git
        run: |
          git config --local user.name "GitHub Workflow"
          git config --local user.email "workflow@github.com"

      - name: Поднятие версий пакетов
        run: |
          yarn lerna version --conventional-prerelease --no-commit-hooks --no-push --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Публикация релиза в Github-реджистри
        run: |
          yarn lerna publish from-git --yes
          git push origin master --follow-tags

        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.ADMIN_KEY }}

